In [1]:
import numpy as np

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#get number of row and column
arr.shape

(3, 3)

In [10]:
#get the whole number of elements
arr.size

9

In [14]:
#specify type of data
np.array(arr,dtype=np.int64)
np.array(arr,dtype=np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
#save numpy array or data in file
x = np.array(arr)
np.save('my_arr',x)
#for load file
y = np.load('my_arr.npy',x)

In [24]:
#build array with zero
x = np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
#build array with one
x = np.ones((4,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
#build array with arbitrary number
x = np.full((3,4),5) #custom_number
x

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
#make square matrix
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#make diag matrix 
x = np.diag([1,2,3,4,5])#putting elements of diag in brakets
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [34]:
#build an array of a sequence ==> np.arange(start,stop,step)
x = np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

In [38]:
#build an a regular exact sequence ==>np.linspace(start,stop,n==defult 50)
x = np.linspace(10,50,11)
x

array([10., 14., 18., 22., 26., 30., 34., 38., 42., 46., 50.])

In [40]:
#linspace and specify endpoint
x = np.linspace(0,25,5)
print(x)
x = np.linspace(0,25,5,endpoint=False)
x

[ 0.    6.25 12.5  18.75 25.  ]


array([ 0.,  5., 10., 15., 20.])

In [49]:
#build matrix with arbitrary dimension
x = np.linspace(0,50,10,endpoint=False).reshape(5,2)
x

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [52]:
#generate random number in differ dimension of matrix ==> np.random.random((row,col))
x = np.random.random((5,2))
x

array([[0.3157776 , 0.61893158],
       [0.00163664, 0.97082021],
       [0.93830262, 0.95416167],
       [0.15957741, 0.82677615],
       [0.71423842, 0.18412432]])

In [56]:
#generate random int number between two custom==>np.random.randint(start,stop,(row,col))
x = np.random.randint(4,15,(5,3))
x

array([[10,  5,  9],
       [13,  6, 14],
       [12,  9,  4],
       [11, 10,  5],
       [12, 13,  5]])

In [59]:
#generate very big or anything matrix for statistical properties and use it(like randint):
#==>np.random.normal(start,stop,size=(row,col))
x = np.random.normal(1,5,size=(1000,1000))
x

array([[ 2.52348514, 12.65111411,  5.89884749, ...,  1.11518778,
         2.86587718,  4.90523125],
       [11.95909055,  8.67513021,  7.98948404, ...,  0.28041331,
        -5.4775552 , -7.14068082],
       [-3.88514282,  4.76574394,  1.28010821, ..., 13.48607334,
         0.66805494, -2.06863989],
       ...,
       [ 4.95135984, -8.70474023, -3.91646166, ...,  4.68045764,
         4.56385692,  3.51188558],
       [-5.62727703,  6.34812701,  2.23220475, ..., -7.84875465,
        -1.45777447,  6.76774501],
       [-4.90696962, -1.66388021,  2.16877027, ..., 11.50229034,
         6.53473894,  4.91449423]])

In [68]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
#delete element from array ==> np.delete(x,index,axis)
x = np.delete(x,2,axis=1)
x

array([[1, 2],
       [4, 5],
       [7, 8]])

In [75]:
#insert value in array ==> np.insert(arr,StartIndex,values,axis) *axis can be None
print(x)
np.insert(x,1,6,1)

[[1 2]
 [4 5]
 [7 8]]


array([[1, 6, 2],
       [4, 6, 5],
       [7, 6, 8]])

In [91]:
#vstack array on each other ==> np.vstack((arr1,arr2))
x = np.array([[1,2]])
y = np.array([[3,4],[5,6]])
z = np.vstack((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
#hstack array(switch number of row and col) ==> np.hstack(arr1,arr2.reshape(arr1Size,arr2Size))
z = np.hstack((y,x.reshape(2,1)))
z

array([[3, 4, 1],
       [5, 6, 2]])

In [118]:
#slice from array in three ways(Notice start and end are the indexes that we specify)
#way one ==> arr[start:end]
#way two ==> arr[start:] ==>until last
#way three ==> arr[:end] ==>start from zero until end
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
z = x[1:3]

In [121]:
#slice from each row and col ==>arr[n1:n2,n3:n4] ==>n1:n2 is slice of row and n3:n4 is slice of col
s = x[1:3,0:2]
s

array([[4, 5],
       [7, 8]])

In [116]:
#build a sequence array and put in a matrix ==> np.arange(start,end,step).reshape(rowSize,colSize)
#Notice that should (start*end)/step == rowSize*colSize
#if dont put step,its default 1
x = np.arange(1,21,2).reshape(2,5)
x

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [122]:
#Important point:if we build an array x and an array y = x[start,end], y is a slice of x and refer to a part of x memory
# so if we change an element of y,corrospanding element in x, changes.for solve this problem,we use copy:
z = np.copy(x[1:,2:])
z

array([[ 6],
       [ 9],
       [12]])

In [135]:
#specify a part of array with condition
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x[x<6]

array([1, 2, 3, 4, 5])

In [154]:
#using sort in different way ==>np.sort(arr,axis)
#axis is default None
x = np.array([[4,5,2,3,1],[7,1,8,4,3],[10,4,7,1,3]])
np.sort(x,1)

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  4,  7,  8],
       [ 1,  3,  4,  7, 10]])

In [163]:
#add corrospond elements of arr1 and arr2
x = np.array([1,2,3])
y = np.array([4,5,6])
np.add(x,y)

array([5, 7, 9])

In [164]:
#divide corrospond elements of arr1 and arr2
np.divide(x,y)

array([0.25, 0.4 , 0.5 ])

In [165]:
#subtract corrospond elements of arr1 and arr2
x = np.array([1,2,3])
y = np.array([7,3,11])
np.subtract(x,y)

array([-6, -1, -8])

In [168]:
#multiply corrospond elements of arr1 and arr2
x = np.array([1,2,3])
y = np.array([4,5,6])
np.multiply(x,y)

array([ 4, 10, 18])

In [172]:
#we can also write math operations like below:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x*y)
print(x+y)
print(x/y)
print(x-y)

[ 4 10 18]
[5 7 9]
[0.25 0.4  0.5 ]
[-3 -3 -3]


In [173]:
#get sqrt from number
np.sqrt(9)

3.0

In [177]:
#get exponential of number or array
np.exp(2) #print 7.3890561
np.exp([1,2,3])

array([ 2.71828183,  7.3890561 , 20.08553692])

In [180]:
#power element of an array or a number ==>np.power(arr,numberOfPow)
x = np.array([1,2,3])
np.power(x,2)

array([1, 4, 9], dtype=int32)

In [182]:
#get medium of arr elements
x = np.array([1,2,3,4,5,6,7,8,12,13,14,15])
np.mean(x)

7.5

In [184]:
#add,divie,moultiple,subtract on all elements of an array
x = np.array([1,2,3,4,5,6,7,8,12,13,14,15])
print(x+2)
print(x*3)
print(x/4)
print(x-5)

[ 3  4  5  6  7  8  9 10 14 15 16 17]
[ 3  6  9 12 15 18 21 24 36 39 42 45]
[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   3.   3.25 3.5  3.75]
[-4 -3 -2 -1  0  1  2  3  7  8  9 10]
